<?php

/**
 * Implements hook_menu().
 * Creates an admin area for the module, which includes menu link and two tabbed pages.
 */
function drupalfi_footer_block_menu() {
  $items = array();

  $items['admin/config/footer_block'] = array(
    'title' => 'Footer block',
    'description' => 'Configuration for footer block',
    'page callback' => 'drupalfi_footer_block_front_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/footer_block/footer_block_front_page'] = array(
    'title' => 'Custom block feature front page',
    'description' => 'Configuration for footer block',
    'page callback' => 'drupalfi_footer_block_front_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/config/footer_block/footer_block'] = array(
    'title' => 'Footer block',
    'description' => 'Configuration for footer block',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('drupalfi_footer_block_settings_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Callback for the default tab.
 *
 * @see drupalfi_footer_block_menu()
 */
function drupalfi_footer_block_front_page() {
  return 'Drupal.fi footer block';
}

/**
 * Implements hook_block_info().
 */
function drupalfi_footer_block_block_info() {
  $blocks['drupalfi_footer_block'] = array(
    'info' => t('Drupal.fi footer block'),
    // Change the cache setting if needed.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function drupalfi_footer_block_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'drupalfi_footer_block':
      $title = drupalfi_footer_block_data('title', $delta);
      $block['subject_array'] = $title;
      $block['subject'] = reset($title);
      $block['content'] = drupalfi_footer_block_data('content', $delta);
      break;
  }
  return $block;
}

/**
 * Provides block content.
 *  @return array
 *    A renderable, translated array containing the markup retrieved from the variable table
 */
function drupalfi_footer_block_data($field, $block_name) {
  // Fetch either the title or the body from the variable table, depending on provided argument.
  $data = ($field == 'title') ? variable_get($block_name . '_title', 'example title') : variable_get($block_name . '_content', 'example content');
  
  // Create the renderable array.
  $content_array = array('#markup' => t($data));
  return $content_array;
}

/**
 * Page callback: example block settings form
 *
 * @see drupalfi_footer_block_menu()
 */
function drupalfi_footer_block_settings_form($form, &$form_state) {
  $form['drupalfi_footer_block_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Block title'),
    '#default_value' => variable_get('drupalfi_footer_block_title', 'example title'),
    '#size' => 20,
    '#description' => t('The block title.'),
    '#required' => TRUE,
  );
  $form['drupalfi_footer_block_content'] = array(
    '#type' => 'textarea',
    '#title' => t('Block content'),
    '#default_value' => variable_get('drupalfi_footer_block_content', 'example content'),
    '#cols' => 60,
    '#rows' => 5,
    '#required' => TRUE,
    '#description' => t('The block content. HTML Allowed. REMEMBER TO TRANSLATE!'),
  );
  return system_settings_form($form);
}
