<?php

/**
* Implements hook_date_format_types().
*/
function drupalfi_date_formats_date_format_types() {
  return array(
    'drupalfi_date_formats_date_only' => t('Date only'),
  );
}
/**
 * Implements hook_date_formats().
 */
function drupalfi_date_formats_date_formats() {
  $formats = array();
  $formats = array(
    array(
      'type' => 'drupalfi_date_formats_date_only',
      'format' => 'd.m.Y',
      'locales' => array(),
    ),
  );
  // save the ne date fortmas into variables
  foreach ($formats as $format) {
    variable_set('date_format_' . $format['type'], $format['format']);
  }
  return $formats;
}
